theme: jekyll-theme-minimal
title: Peter Whitman
description: Remote sensing researcher at the U.S. Environmental Protection Agency (EPA) Office of Research and Development
keywords: [remote sensing, research, GIS, geospatial, water quality, image processing, machine learning]
author: Peter Whitman
logo: https://github.com/peterwhitman/peterwhitman.github.io/images/headshot_square.JPG
image: https://github.com/peterwhitman/peterwhitman.github.io/images/PA281604.JPG
social:
  name: Peter Whitman
  links:
    - https://www.linkedin.com/in/peter-whitman/
    - https://github.com/peterwhitman
    - https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=LsvNktAAAAAJ
    - https://orcid.org/0000-0001-9207-0177
    - https://www.researchgate.net/profile/Peter-Whitman-2
webmaster_verifications:
  google: gCAElCtvSFWnGWFBRbIu8a8Wsf2ieZ_ENA-alOp8cMk
  bing: E14272C61A07D159F6965258035068CE
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

