theme: jekyll-theme-minimal
title: Peter Whitman
tagline: Personal Website
description: "Remote sensing researcher at the U.S. Environmental Protection Agency (EPA) Office of Research and Development"
keywords: "remote sensing, research, GIS, geospatial, water quality, image processing"
author: Peter Whitman
social:
  name: Peter Whitman
  links:
    - https://www.linkedin.com/in/peter-whitman/
    - https://github.com/peterwhitman
    - https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=LsvNktAAAAAJ
    - https://orcid.org/0000-0001-9207-0177

