theme: jekyll-theme-minimal
title: Peter Whitman's Personal Website
author: Peter Whitman
description: "Personal Website"
keywords: "remote sensing, research, GIS, geospatial, water quality, image processing"
